config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :user do
    resources :questions
  end

  resources :questions do
    resources :answers, only: [:create, :new, :destroy, :update, :edit]
  end

  resources :answers, only: [:new, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  validates :culture, presence: true

  has_many :houses, through: :roles
end

app/models/favchar.rb
class FavChar < ApplicationRecord
belongs_to :user
belongs_to :character
end

app/models/favcomic.rb
class FavHouse < ApplicationRecord
belongs_to :user
belongs_to :house
end

app/models/house.rb
class House < ApplicationRecord
  validates :name, presence: true
  validates :region, presence: true


  has_many :characters, through: :roles

end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence:true
  validates :body, presence:true

  belongs_to :user
  has_many :answers

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

def create
  @question = Question.find(params[:question_id])
  @user = current_user
  @answer = Answer.new(answer_params)
  @answer.question = @question
  @answer.user = @user

  if @answer.save
    flash[:notice] = "Answer added successfully"
    redirect_to question_path(@question)
  else
    flash[:notice] = @answer.errors.full_messages
    @creator = @question.user
    @answers = @question.answers
    @answer = Answer.new
    render "questions/show"
  end
end

  def new
      @question = Question.find(params[:question_id])
      @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])

  if @answer.update(answer_params)
    redirect_to @question, notice: 'Answer was successfully updated.'
  else
    render :edit
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find_by(user: current_user, question: @question)
    @answer.destroy
    redirect_to question_path(@question), notice: 'Question was successfully Deleted.'
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :question_id)
  end

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Please log in to use this feature"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :password, :password_confirmation, :remember_me])
  end

  def authenticate_admin!
    unless user_signed_in? && current_user.admin?
      redirect_to root_path, notice: "You're not an admin, pal"
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:update, :destroy]

def index
end


def search
end

private
  def page
    params[:page] || 1
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def index
    @questions = Question.all

  end

  def show
    @question = Question.find(params[:id])
    @creator = @question.user
    @answer = Answer.new
    @answers = @question.answers
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    @question.user = current_user

    if @question.save
      flash[:notice] = "Question added successfully"
      redirect_to question_path(@question)
    else
      flash[:notice] = @question.errors.full_messages
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def authorize_user
    unless user_signed_in? || (current_user)
      flash[:notice] = "Please log in to use this feature"
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Post</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheets" href="response.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>
  </head>
  <body style="background-color: #F8F8F8">
    <%= form_for [question, answer] do |f| %>
      <% if answer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
          <ul>
          <% answer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
         <div class="small-14 small-centered columns">
           <div class="response-panel">
             <form>
               <div class="row collapse">
                 <div class="small-14  columns">
                   <%=f.text_area :body, placeholder:"Respond Here", style:"box-shadow: 0 0px 10px 0 rgba(0, 0, 0, 0.16), 0 20px 10px 0 rgba(0, 0, 0, 0.12);"%>
                 </div>
               </div>
             </form>
             <div class="small-5 small-centered columns">
             <%= f.submit "Submit", class:"button round", style:"box-shadow: 0px 5px 5px #B2B2B2"%>
            </div>
           </div>
         </div>
        </div>
      <% end %>
  </body>
</html>

app/views/answers/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit</title>
  </head>
  <body style="background-color: #F8F8F8">
    <div class ="editcomment">
      <h1>Edit Comment</h1>

      <%= render 'answer_form', question: @question, answer: @answer %>

      <h3 style="text-align:center"><%= link_to 'Back', @question %></h3>
    </div>
  </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
    <link rel="stylesheets" href="home.scss">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/js/foundation.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/js/plugins/foundation.orbit.js"></script>
  </head>
  <br><br>
  <body style="background-color: #F8F8F8">
    <div class="small-3 small-centered columns">
  <a href="#openModal"> <img src="http://logos-download.com/wp-content/uploads/2016/09/Game_of_Thrones_logo_logotype_wordmark.png" alt="Not Available" style="width:100;height:100px;"></a>
    </div>

    <ul class="slides">
        <input type="radio" name="radio-btn" id="img-1" checked />
        <li class="slide-container">
    		<div class="slide">
    			<img src="http://www.wallpapermade.com/images/wallpapers/originals/daenerys-targaryen-emilia-clarke-game-of-thrones-4k-portrait-wallpaper-6171.jpg" />
            </div>
    		<div class="nav">
    			<label for="img-6" class="prev">&#x2039;</label>
    			<label for="img-2" class="next">&#x203a;</label>
    		</div>
        </li>

        <input type="radio" name="radio-btn" id="img-2" />
        <li class="slide-container">
            <div class="slide">
              <img src="http://backgrounds4k.net/wp-content/uploads/2016/01/Game-of-Thrones-photos.jpg" />
            </div>
    		<div class="nav">
    			<label for="img-1" class="prev">&#x2039;</label>
    			<label for="img-3" class="next">&#x203a;</label>
    		</div>
        </li>

        <input type="radio" name="radio-btn" id="img-3" />
        <li class="slide-container">
            <div class="slide">
              <img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxNTY3NzEzN15BMl5BanBnXkFtZTgwNzgyMDM2ODE@._V1_.jpg" />
            </div>
    		<div class="nav">
    			<label for="img-2" class="prev">&#x2039;</label>
    			<label for="img-4" class="next">&#x203a;</label>
    		</div>
        </li>

        <input type="radio" name="radio-btn" id="img-4" />
        <li class="slide-container">
            <div class="slide">
              <img src="http://www.wallpapermade.com/images/wallpapers/originals/sandor-the-hound-clegane-rory-mccann-game-of-thrones-4k-portrait-wallpaper-6160.jpg" />
            </div>
    		<div class="nav">
    			<label for="img-3" class="prev">&#x2039;</label>
    			<label for="img-5" class="next">&#x203a;</label>
    		</div>
        </li>

        <input type="radio" name="radio-btn" id="img-5" />
        <li class="slide-container">
            <div class="slide">
              <img src="http://wallup.net/wp-content/uploads/2016/05/02/43255-anime-Game_of_Thrones-Brandon_Stark-Cersei_Lannister-Jaime_Lannister-Tyrion_Lannister-Daenerys_Targaryen-Arya_Stark-Sansa_Stark-Robb_Stark-Catelyn_Stark-Joffrey_Baratheon-The_Hound-Jon_Snow.jpg" />
            </div>
    		<div class="nav">
    			<label for="img-4" class="prev">&#x2039;</label>
    			<label for="img-6" class="next">&#x203a;</label>
    		</div>
        </li>

        <input type="radio" name="radio-btn" id="img-6" />
        <li class="slide-container">
            <div class="slide">
              <img src="https://wallpaperscraft.com/image/game_of_thrones_lena_headey_cersei_lannister_94601_3840x2160.jpg" />
            </div>
    		<div class="nav">
    			<label for="img-5" class="prev">&#x2039;</label>
    			<label for="img-1" class="next">&#x203a;</label>
    		</div>
        </li>

        <li class="nav-dots">
          <label for="img-1" class="nav-dot" id="img-dot-1"></label>
          <label for="img-2" class="nav-dot" id="img-dot-2"></label>
          <label for="img-3" class="nav-dot" id="img-dot-3"></label>
          <label for="img-4" class="nav-dot" id="img-dot-4"></label>
          <label for="img-5" class="nav-dot" id="img-dot-5"></label>
          <label for="img-6" class="nav-dot" id="img-dot-6"></label>
        </li>
    </ul>
    <div id="openModal" class="modalDialog">
      <div>	<a href="#close" title="Close" class="close">X</a>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/E_84ZhuEx4c" frameborder="0" allowfullscreen></iframe>      </div>
    </div>

    <br>
    <div>
  <a href="#open"><div id="characters"></a>
      </div>
      <div id="open" class="modalDialog">
        <div>	<a href="#close" title="Close" class="close">X</a>
      </div>
    </div>
    <br>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application',  :media => "all" %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/js/plugins/foundation.dropdownMenu.js"></script>
  </head>
  <body>
    <div class="top-bar" id="" data-animate="hinge-in-from-top spin-out" style="background-color: #282828" >
    <div class="small-3 small-push-1 columns"><i class="fi-crown"></i><%= link_to "GOT-search", root_path, class:"links"%></div>
      <div class="top-bar-right" style="background-color: #282828">
        <ul class="dropdown menu" data-dropdown-menu style="background-color: #282828">
          <li><%= link_to "Discussion Board", questions_path, class:"links" %></li>
          <li>
            <% if user_signed_in? %>
            <a href="#" class="links">Account Settings</a>
            <%- else -%>
            <a href="#" class="links">Create Account</a>
            <% end %>
            <ul class="menu vertical" style="background-color: #282828">
              <% if user_signed_in? %>

              <li></li>
              <li><%= link_to "User Profile", edit_user_registration_path, class:"links" %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"links"%></li>
              <%- else -%>
              <li><%= link_to "Sign In", new_user_session_path, class:"links" %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, class:"links" %></li>
            </ul>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
    <script>
    $(document).foundation();
    </script>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/questions/_form.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title>Add a Question</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheets" href="signup.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>
  </head>
  <body style="background-color: #F8F8F8">
    <%= form_for(question, html: {:multipart => true }) do |f| %>
      <% if question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
          <ul>
            <% question.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
         <div class="large-6 large-centered columns">
           <div class="post-panel">
             <form>
               <div class="row collapse">
                 <div class="small-12 large-centered columns">
                   <%= f.text_area :title, placeholder:"Title"%>
                 </div>
               </div>
               <div class="row collapse">
                 <div class="small-12 large-centered columns">
                   <%= f.text_area :body, placeholder:"Describe your post" %>
                 </div>
                   <div class="small-4 small-centered columns">
                   <%= f.submit "Submit" , class:"button round"%>
                 </div>
               </div>
               <% end %>
             </form>
           </div>
         </div>
       </div>
  </body>
</html>

app/views/questions/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit</title>
  </head>
  <body style="background-color: #F8F8F8">
    <br>
    <div class="editpost">
    <h1>Editing <%=@question.title%></h1>

    <%= render 'form', question: @question %>

    <h3 style="text-align:center"><%= link_to 'Back', @question %></h3>

  </div>
  </body>
</html>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Discussion Board</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
    <link rel="stylesheets" href="discussion.scss">
    <script src="//use.edgefonts.net/unifrakturmaguntia.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>
  </head>
  <body style="background-color: #F8F8F8">
  <div class="small-8 large-centered columns">
    <table class="hover">
      <thead>
        <center><img src="https://image.ibb.co/jHXqov/Stark_icon_copy.png" alt="Stark_icon_copy" border="0" class="imageheader"></center>
        <center><%= link_to "Add New Question", new_question_path, class:"button round", style:"box-shadow: 0px 5px 5px #B2B2B2" %></center>
      </thead>
      <tbody style="box-shadow: 0 0px 10px 0 rgba(0, 0, 0, 0.16), 0 20px 10px 0 rgba(0, 0, 0, 0.12);">
        <% @questions.each do |question| %>
        <tr>
          <td><%= link_to question.title, question_path(question) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </body>
</html>

app/views/questions/new.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title>Post</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheets" href="signup.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>
  </head>
  <body style="background-color: #F8F8F8">
    <br>
    <div class="postform">
    <h1>New Post</h1>
    <%= render 'form', question: @question %>
    <h3 style="text-align:center"><%= link_to 'Back', questions_path %></h3>
    <br>
  </div>
  </body>
</html>

app/views/questions/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheets" href="discussion.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>
  </head>
  <br>
  <body style="background-color: #F8F8F8">
    <div class="small-9 small-centered columns">
      <br>
      <div class="card" style="box-shadow: 0 0px 10px 0 rgba(0, 0, 0, 0.16), 0 20px 10px 0 rgba(0, 0, 0, 0.12);">
        <div class="medium-6 large-8 columns">
          <h3><%=@question.title%></h3>
          <div class="indented comment">
            <p><%=@question.body%></p>
            <% if @creator == current_user %>
            <%= link_to "Edit", edit_question_path(@question) %> |
            <%= link_to "Remove #{@question.title}", @question, method: :delete%>
            <% end %>
          </div>
          <br><br>
          <% @answers.each do |answer| %>
          <div class="indented comment">
            <section class="top">
              <h6 class="byline">
                <i class="icon"></i><%= answer.user.first_name%>
                <small>said
                </small>
              </h6>
            </section>
            <p><%= answer.body %></p>
            <% if @creator == current_user %>
            <%= link_to "Edit Comment", edit_question_answer_path(@question,answer) %>
            <%= link_to "Remove Comment", question_answer_path(@question,answer), method: :delete%>

            <% end %>

          </div>
          <% end %>
        </div>
      </div>
      <%= render "answers/answer_form", question: @question, answer: @answer %>
    </div>
  </body>
</html>